import { readdir } from "fs/promises";
import { join, relative } from "path";

const buildDir = process.env.ODE_WEB_BUILD_DIR?.trim()
  || join(process.cwd(), "packages", "web-ui", "build");
const outputFile = join(process.cwd(), "packages", "core", "web", "embedded-assets.ts");

async function listFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listFiles(fullPath));
      continue;
    }
    if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files;
}

function toAssetPath(filePath: string): string {
  const rel = relative(buildDir, filePath).split("\\").join("/");
  return `/${rel}`;
}

async function buildEmbeddedAssets(): Promise<void> {
  const files = await listFiles(buildDir);
  const entries: Array<{ path: string; base64: string }> = [];

  for (const filePath of files) {
    const data = await Bun.file(filePath).arrayBuffer();
    const base64 = Buffer.from(data).toString("base64");
    entries.push({ path: toAssetPath(filePath), base64 });
  }

  entries.sort((a, b) => a.path.localeCompare(b.path));

  const lines: string[] = [
    "// This file is generated by scripts/embed-web-assets.ts. Do not edit.",
    "export const EMBEDDED_ASSETS: Record<string, string> = {",
  ];

  for (const entry of entries) {
    lines.push(`  ${JSON.stringify(entry.path)}: ${JSON.stringify(entry.base64)},`);
  }

  lines.push("};");
  lines.push("export const HAS_EMBEDDED_ASSETS = Object.keys(EMBEDDED_ASSETS).length > 0;");
  lines.push("");

  await Bun.write(outputFile, lines.join("\n"));
}

await buildEmbeddedAssets();
